/**
 * Lightweight visual hints (accent color + font) for each template key, used
 * by small UI chips (admin list, builder picker) that don't need to render
 * the full template component. Keep keys in sync with Components/Templates/registry.js.
 */
export const TEMPLATE_SWATCHES = {
    modern: { accent: 'bg-indigo-500', font: 'font-sans' },
    classic: { accent: 'bg-gray-800', font: 'font-serif' },
    minimal: { accent: 'bg-gray-300', font: 'font-sans' },
    professional: { accent: 'bg-slate-700', font: 'font-sans' },
    executive: { accent: 'bg-amber-500', font: 'font-serif' },
    creative: { accent: 'bg-violet-500', font: 'font-sans' },
    student: { accent: 'bg-sky-500', font: 'font-sans' },
    compact: { accent: 'bg-gray-500', font: 'font-sans' },
    elegant: { accent: 'bg-rose-400', font: 'font-serif' },
    technical: { accent: 'bg-teal-500', font: 'font-mono' },
    bold: { accent: 'bg-black', font: 'font-sans' },
    corporate: { accent: 'bg-slate-900', font: 'font-sans' },
    timeline: { accent: 'bg-blue-500', font: 'font-sans' },
    infographic: { accent: 'bg-orange-500', font: 'font-sans' },
    monochrome: { accent: 'bg-gray-900', font: 'font-sans' },
    photo: { accent: 'bg-indigo-600', font: 'font-sans' },
    twocolumn: { accent: 'bg-emerald-600', font: 'font-sans' },
    academic: { accent: 'bg-stone-700', font: 'font-serif' },
    startup: { accent: 'bg-purple-500', font: 'font-sans' },
    swiss: { accent: 'bg-red-600', font: 'font-sans' },
    sidebarnavy: { accent: 'bg-slate-900', font: 'font-sans' },
    sidebarforest: { accent: 'bg-emerald-900', font: 'font-sans' },
    sidebarplum: { accent: 'bg-purple-900', font: 'font-sans' },
    bannercrimson: { accent: 'bg-rose-600', font: 'font-sans' },
    bannerteal: { accent: 'bg-teal-600', font: 'font-sans' },
    bannerslate: { accent: 'bg-slate-600', font: 'font-sans' },
    iconaccentblue: { accent: 'bg-blue-600', font: 'font-sans' },
    iconaccentcoral: { accent: 'bg-orange-600', font: 'font-sans' },
    iconaccentolive: { accent: 'bg-lime-700', font: 'font-sans' },
    ledgercharcoal: { accent: 'bg-gray-700', font: 'font-sans' },
    ledgersteel: { accent: 'bg-slate-700', font: 'font-sans' },
    ledgersand: { accent: 'bg-stone-700', font: 'font-sans' },
    portfoliomagenta: { accent: 'bg-pink-600', font: 'font-sans' },
    portfoliocyan: { accent: 'bg-cyan-700', font: 'font-sans' },
    portfolioamber: { accent: 'bg-amber-700', font: 'font-sans' },
    splitheaderindigo: { accent: 'bg-indigo-600', font: 'font-sans' },
    splitheaderemerald: { accent: 'bg-emerald-600', font: 'font-sans' },
    splitheadermaroon: { accent: 'bg-red-800', font: 'font-sans' },
    cardsky: { accent: 'bg-sky-500', font: 'font-sans' },
    cardlime: { accent: 'bg-lime-500', font: 'font-sans' },
    cardgrape: { accent: 'bg-violet-500', font: 'font-sans' },
    ribbonruby: { accent: 'bg-rose-600', font: 'font-sans' },
    ribboncobalt: { accent: 'bg-blue-600', font: 'font-sans' },
    ribbonmustard: { accent: 'bg-yellow-600', font: 'font-sans' },
    stackedplum: { accent: 'bg-purple-600', font: 'font-sans' },
    stackedteal: { accent: 'bg-teal-600', font: 'font-sans' },
    stackedgray: { accent: 'bg-gray-600', font: 'font-sans' },
    framenavy: { accent: 'bg-slate-800', font: 'font-serif' },
    framebronze: { accent: 'bg-amber-800', font: 'font-serif' },
    frameforest: { accent: 'bg-emerald-800', font: 'font-serif' },
    diagonal: { accent: 'bg-cyan-600', font: 'font-sans' },
    newspaper: { accent: 'bg-gray-900', font: 'font-serif' },
    badge: { accent: 'bg-fuchsia-600', font: 'font-sans' },
    underline: { accent: 'bg-amber-500', font: 'font-sans' },
    gridblock: { accent: 'bg-sky-600', font: 'font-sans' },
    watermark: { accent: 'bg-slate-500', font: 'font-sans' },
    terminal: { accent: 'bg-lime-400', font: 'font-mono' },
    boxedtab: { accent: 'bg-orange-600', font: 'font-sans' },
    zigzag: { accent: 'bg-violet-600', font: 'font-sans' },
    dossier: { accent: 'bg-amber-800', font: 'font-sans' },
};

export function templateSwatch(key) {
    return TEMPLATE_SWATCHES[key] ?? { accent: 'bg-gray-400', font: 'font-sans' };
}
